"""initial schema

Revision ID: e5b6d493b126
Revises: 
Create Date: 2026-06-28 14:42:30.974844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b6d493b126'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarot_cards',
    sa.Column('primary_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_ru', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('arcana', sa.Enum('major', 'minor', name='arcana', native_enum=False), nullable=False),
    sa.Column('suit', sa.Enum('wands', 'cups', 'swords', 'pentacles', name='suit', native_enum=False), nullable=True),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_index(op.f('ix_tarot_cards_code'), 'tarot_cards', ['code'], unique=True)
    op.create_table('users',
    sa.Column('primary_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), server_default='ru', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('readings',
    sa.Column('primary_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spread_type', sa.Enum('card_of_day', 'past_present_future', 'free_question', name='spreadtype', native_enum=False), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'generating', 'completed', 'failed', name='readingstatus', native_enum=False), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.primary_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_index(op.f('ix_readings_user_id'), 'readings', ['user_id'], unique=False)
    op.create_index('ix_readings_user_id_created_at', 'readings', ['user_id', 'created_at'], unique=False)
    op.create_table('reading_cards',
    sa.Column('primary_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('tarot_card_id', sa.Integer(), nullable=False),
    sa.Column('position_index', sa.SmallInteger(), nullable=False),
    sa.Column('position_key', sa.Enum('day', 'past', 'present', 'future', 'insight_1', 'insight_2', 'insight_3', name='cardpositionkey', native_enum=False), nullable=False),
    sa.Column('is_reversed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.primary_key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarot_card_id'], ['tarot_cards.primary_key'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('primary_key'),
    sa.UniqueConstraint('reading_id', 'position_index', name='uq_reading_cards_reading_position')
    )
    op.create_index(op.f('ix_reading_cards_reading_id'), 'reading_cards', ['reading_id'], unique=False)
    op.create_index(op.f('ix_reading_cards_tarot_card_id'), 'reading_cards', ['tarot_card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_cards_tarot_card_id'), table_name='reading_cards')
    op.drop_index(op.f('ix_reading_cards_reading_id'), table_name='reading_cards')
    op.drop_table('reading_cards')
    op.drop_index('ix_readings_user_id_created_at', table_name='readings')
    op.drop_index(op.f('ix_readings_user_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tarot_cards_code'), table_name='tarot_cards')
    op.drop_table('tarot_cards')
    # ### end Alembic commands ###
